$(function(){
  $('.kia').click(function(){
    window.open('https://eunzero.github.io/kia');
  });
  $('.iwc').click(function(){
    window.open('https://eunzero.github.io/iwc');
  });
  $('.tour').click(function(){
    window.open('https://eunzero.github.io/tour');
  });
  $('.megabox').click(function(){
    window.open('https://eunzero.github.io/megabox');
  });
  $('.kakao').click(function(){
    window.open('https://eunzero.github.io/kakaocorp');
  });
})